### Base config
@baseUrl = http://localhost:8080
@adminEmail = admin@example.com
@adminPassword = password
@token = {{loginAdmin.response.body.$.accessToken}}

### 1) Login as seeded admin (from DataSeeder)
# @name loginAdmin
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
	"email": "{{adminEmail}}",
	"password": "{{adminPassword}}"
}

### Test all user creations.
### Test user credentials: 
    ### user actions <-> non user actions
    ### operator actions <-> non operator actions
    ### admin actions <-> non admin actions

### test updating, delete, read (all repo methods)


### duplicate all tests into /test